services:
  mkdocs:
    build: .
    volumes:
      - .:/docs
      - /docs/node_modules # Persist node_modules for faster subsequent builds
    ports:
      - "8000:8000"
      - "35729:35729"
    stdin_open: true
    tty: true
    # Override the default command to ensure both Sass and MkDocs run
    command: sh -c "npm run dev & mkdocs serve --dev-addr=0.0.0.0:8000 --livereload"
