services:
  mkdocs:
    build: .
    volumes:
      - .:/docs
      - /docs/node_modules # Persist node_modules for faster subsequent builds
    ports:
      - "8000:8000"
      - "35729:35729"
    stdin_open: true
    tty: true
    # Use container entrypoint to run processes
