#!/bin/sh
## . "$(dirname "$0")/_/husky.sh"

# Check if the hook should be skipped
if [ "$SKIP_HOOK" = "true" ]; then
  exit 0
fi

# Start MkDocs in the background
mkdocs serve --quiet &

# Capture the PID of the MkDocs server
MKDOCS_PID=$!

# Uncomment the following line to run pa11y-test before commit
# npm run pa11y-test

# Stop MkDocs server
kill $MKDOCS_PID

# Stage the generated CSV file
git add output/pa11y-results.csv

exit 0
